add check to differentiate the version either enterprise or community
Alfresco/alfresco-android-kotlin-api pull request #2
Opened 2021-08-12 07:13 UTC by aman-alfresco

2021-08-12 07:25 UTC, agologan requested changes
Current version just assumes `isContentServiceInstalled` as a prerequisite in order to return whether or not this is an enterprise installation.
This is unexpected and brittle, a better api would just add a fun along the lines of `isEnterpriseDistribution(endpoint: String)`

2021-08-12 14:18 UTC, agologan requested changes
This is better but the call code is now duplicated between the two functions, maybe extract it in a new function?
Also there is no caching involved between the two calls? Are you ok with doing the call twice?

2021-08-12 15:42 UTC, aman-alfresco commented on auth/src/main/java/com/alfresco/auth/DiscoveryService.kt
> +     * Check whether it's enterprise distribution or not on [endpoint].
done

2021-08-16 04:30 UTC, aman-alfresco commented
> This is better but the call code is now duplicated between the two functions, maybe extract it in a new function?
> Also there is no caching involved between the two calls? Are you ok with doing the call twice?

yes. ok with that

2021-08-16 07:32 UTC, merged